
language: node_js
node_js:
  - '8'
before_install:
  - cd ./npm
  - npm i -g makeshift && makeshift -r https://registry.npmjs.org
install:
  - npm install
script:
  - npm test
  - set -e
  - ../deploy.sh
branches:
  only:
  - develop
  - master